package primer_final.idiomas;


import java.util.ListResourceBundle;


public class language_de extends ListResourceBundle {
    private static final Object[][] CONTENTS = {
        {"iniciarSesion",                   "Anmelden"},
        {"nroCuenta",                       "Konto"},
        {"pin",                             "PIN"},
        {"terminarSimulacion",              "Simulation Beenden"},
        {"agregar",                         "Hinzufügen"},
        {"documento",                       "Dokument"},
        {"apellido",                        "Nachname"},
        {"nombre",                          "Name"},
        {"correo",                          "E-Mail"},
        {"telefono",                        "Telefonnummer"},
        {"acceso",                          "Zugriff"},
        {"agregarCuenta",                   "Konto Hinzügen"},
        {"agregarServicio",                 "Dienstleistung Hinzufügen"},
        {"direccion",                       "Addresse"},
        {"monto",                           "Betrag"},
        {"nombreServicio",                  "Name"},
        {"icono",                           "Symbol"},
        {"descripcion",                     "Beschreibung"},
        {"deposito",                        "Einzahlen"},
        {"hacerDeposito",                   "Einzahlen"},
        {"desbloquear",                     "Entsperren"},
        {"desbloquearCuenta",               "Konto Entsperren"},
        {"eliminar",                        "Löschen"},
        {"eliminarCuenta",                  "Konto Löschen"},
        {"eliminarServicio",                "Dienstleistung Löschen"},
        {"nombreServicio",                  "Name"},
        {"serviciosDisponibles",            "Verfügbare Dienstleistungen"},
        {"efectuarTransferencia",           "Überweisung tätigen"},
        {"pinTransferencia",                "Überweisungs PIN"},
        {"transferencia",                   "Überweisung"},
        {"saldoActual",                     "Guthaben"},
        {"informacionCuenta",               "Kontoübersicht"},
        {"titularNombre",                   "Eigentümer"},
        {"cerrarSesion",                    "Abmelden"},
        {"informe",                         "Kontoberricht"},
        {"ayuda",                           "Hilfe"},
        {"pagarServicio",                   "Dienstleistung bezahlen"},
        {"tituloVentana",                   "Simulation Web Banking"},
        {"bienvenidoNombre",                "Wilkommen {0}"},
        {"saldo",                           "Guthaben"},
        {"queDeseaHacer",                   "Was möchten sie tun?"},
        {"idiomaNombre",                    "Deutsch"},
        
        {"loginNoExitoso",                  "Anmelden nicht möglich"},
        {"loginErrorMessage",               "Wir konnten Sie nicht anmelden. Bitte Eingabe überprüfen und erneut versuchen."},
        {"dbErrorTitulo",                   "Datenbankfehler"}, 
        {"dbErrorMensaje",                  "Aktion konnte nicht ausgeführt werden. Bitte Eingabe überprüfen und erneut versuchen."},
        {"pinTransferenciaNoValido",        "Falscher Überweisungspin. Bitter überprüfen und erneut versuchen."},
        {"pinNoValidoTitulo",               "Falscher PIN"},
        {"saldoInsuficienteTitulo",         "Unzureichendes Guthaben"},
        {"saldoInsuficiente",               "Ihr Guthaben genügt nicht für diese Überweisung"},
        {"servicioPagadoTitulo",            "Dienstleistung bezahlt"},
        {"servicioPagado",                  "Sie haben die Dienstleistung \"{2}\" mit Ihrem Konto {1} bezahlt. Die Summe betrug {3}.\nZeitstempel: {0}"},
        {"transferenciaRealizadaTitulo",    "Überweisung getätigt"},
        {"transferenciaRealizada",          "Sie haben {3} überwiesen\nVon: {1}\nAn: {2}\nZeitstempel: {0}"},
        {"pdfOpenErrorTitulo",              "Fehler beim öffnen des PDF"},
        {"pdfOpenError",                    "Wir konnten die Hilfsdatei nicht öffnen. Stellen Sie sicher, dass Sie über eine Anwendung zum lesen von .pdf Dateien verfügen."},
        {"inputNoCorrectoTitulo",           "Ungültige Eingabe"},
        {"inputNoCorrecto",                 "Eine Ihrer Eingaben konnte vom System nicht interpretiert werden. Bitte Eingaben überprüfen."},
        {"cuentaNoEncontradaTitulo",        "Konto nicht gefunden"},
        {"cuentaNoEncontrada",              "Wir konnten diese Konto nicht finden. Bitte Eingaben überprüfen"},
        {"tutorialArchivo",                 "FAQ_Lp2_DE.pdf"},
        {"depositoConfirmacionTitulo",      "Einzahlung getätigt"},
        {"depositoConfirmacion",            "Sie haben in ihr Konto {1} {2} eingezahlt\nZeitstempel: {0}"},
        {"desbloqueoConfirmacionTitulo",    "Konto entsperrt"},
        {"desbloqueoConfirmacion",          "Das Konto {0} wurde entsperrt"},
        {"cuentaYaExisteTitulo",            "Konto existiert bereits"},
        {"cuentaYaExiste",                  "Konto existiert bereits und konnte daher nicht erstellt werden!"},
        {"servicioYaExisteTitulo",          "Dienstleistung existiert bereits"},
        {"servicioYaExiste",                "Dienstleistung existiert bereits und konnte daher nicht erstellt werden!"},
        {"servicioNoExisteTitulo",          "Dienstleistung nicht gefunden"},
        {"servicioNoExiste",                "Die angeforderte Dienstleistung konnte nicht gefunden werden"},
        {"cuentaNoExisteTitulo",            "Konto nicht gefunden"},
        {"cuentaNoExiste",                  "Dieses Konto scheint nicht zu existieren. Vergewissern Sie sich bitte, dass ihre Eingaben korrekt sind"},
        {"borrarPropioErrorTitulo",         "Selbstzerstörung"},
        {"borrarPropioError",               "Selbstzerstörung überlassen wir lieber den Filmen, also bitte wählen Sie ein anderes Konto als das eigene!"},
        {"cuentaCreadaTitulo",              "Konto erstellt"},
        {"cuentaCreada",                    "Konto erfolgreich erstellt.\nKontonummer: {0}\nPIN: {1}\nÜberweisungspin: {2}"},
        {"servicioCreadoTitulo",            "Dienstleistung erstellt"},
        {"servicioCreado",                  "Die Dienstleistung wurde erstellt.\nKontonummer: {0}\nName: {1}\nBetrag: {2}"},
        {"cuentaEliminadaTitulo",           "Konto gelöscht"},
        {"cuentaEliminada",                 "Das Konto mit Nummer {0} wurde gelöscht"},
        {"servicioEliminadoTitulo",         "Dienstleistung gelöscht"},
        {"servicioEliminado",               "Die Dienstleistung \"{0}\" wurde gelöscht"},
        {"cuentaBloqueadaError",            "Ihr Konto ist gesperrt"},
        {"montoNegativoTitulo",             "Negativer Betrag"},
        {"montoNegativo",                   "Es sind keine negativen Beträge für diese Aktion erlaubt"},
        {"cuenta",                          "Konto"},
        {"titular",                         "Eigentümer"},
        {"fecha",                           "Datum und Uhrzeit"},
        {"informe",                         "Bericht"},
        {"id",                              "ID"},
        {"transferenciasRealizadas",        "Getätigte Überweisungen"},
        {"transferenciasRecibidas",         "Empfangene Überweisungen"},
        {"transferenciasAServicios",        "Überweisungen an Dienstleistungen"},
        {"transaccionFallidaTitulo",        "Überweisung fehlgeschlagen"},
        {"transaccionFallida",              "Überweisung fehlgeschlagen, bitt Kontonummer überprüfen."}
    };
    @Override
    protected Object[][] getContents() {
        return CONTENTS;
    }
    
}
